[package]
name = "l004"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^4"
actix-rt = "2.7.0"
actix-files = "0.6.1"
dotenv = "0.15.0"
postgres = "0.19.3"
rpassword = "6.0.1"